<?xml version="1.0" encoding="UTF-8" standalone="no"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://www.cmis.org/2008/05" xmlns:ns2="http://cxf.apache.org/bindings/xformat" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.cmis.org/ns/1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="MultiFilingService" targetNamespace="http://www.cmis.org/ns/1.0">
  <wsdl:import location="http://localhost:8080/alfresco/cmis/MultiFilingService?wsdl=MultiFilingServicePort.wsdl" namespace="http://www.cmis.org/2008/05">
    </wsdl:import>
  <wsdl:message name="removeObjectFromFolder">
    <wsdl:part element="ns1:removeObjectFromFolder" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="addObjectToFolder">
    <wsdl:part element="ns1:addObjectToFolder" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="addObjectToFolderResponse">
    <wsdl:part element="ns1:addObjectToFolderResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="removeObjectFromFolderResponse">
    <wsdl:part element="ns1:removeObjectFromFolderResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:binding name="MultiFilingServiceSoapBinding" type="ns1:MultiFilingServicePort">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="removeObjectFromFolder">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="removeObjectFromFolder">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="removeObjectFromFolderResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="ObjectNotFoundException">
        <soap:fault name="ObjectNotFoundException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="NotInFolderException">
        <soap:fault name="NotInFolderException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="UpdateConflictException">
        <soap:fault name="UpdateConflictException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="RuntimeException">
        <soap:fault name="RuntimeException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ConstraintViolationException">
        <soap:fault name="ConstraintViolationException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="InvalidArgumentException">
        <soap:fault name="InvalidArgumentException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="OperationNotSupportedException">
        <soap:fault name="OperationNotSupportedException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="FolderNotValidException">
        <soap:fault name="FolderNotValidException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="PermissionDeniedException">
        <soap:fault name="PermissionDeniedException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="addObjectToFolder">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="addObjectToFolder">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="addObjectToFolderResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="ObjectNotFoundException">
        <soap:fault name="ObjectNotFoundException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="UpdateConflictException">
        <soap:fault name="UpdateConflictException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="RuntimeException">
        <soap:fault name="RuntimeException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ConstraintViolationException">
        <soap:fault name="ConstraintViolationException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="InvalidArgumentException">
        <soap:fault name="InvalidArgumentException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="OperationNotSupportedException">
        <soap:fault name="OperationNotSupportedException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="FolderNotValidException">
        <soap:fault name="FolderNotValidException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="PermissionDeniedException">
        <soap:fault name="PermissionDeniedException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="MultiFilingService">
    <wsdl:port binding="tns:MultiFilingServiceSoapBinding" name="MultiFilingServicePort">
      <soap:address location="http://localhost:8080/alfresco/cmis/MultiFilingService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>